module com.github.moaxcp.xeleven.client {
    requires static lombok;
    requires org.newsclub.net.unix;
    exports com.github.moaxcp.x11client;
    exports com.github.moaxcp.x11client.experimental;
    exports com.github.moaxcp.x11client.protocol;
    exports com.github.moaxcp.x11client.protocol.xproto;
    exports com.github.moaxcp.x11client.protocol.bigreq;
    exports com.github.moaxcp.x11client.protocol.composite;
    exports com.github.moaxcp.x11client.protocol.damage;
    exports com.github.moaxcp.x11client.protocol.dpms;
    exports com.github.moaxcp.x11client.protocol.dri2;
    exports com.github.moaxcp.x11client.protocol.dri3;
    exports com.github.moaxcp.x11client.protocol.ge;
    exports com.github.moaxcp.x11client.protocol.glx;
    exports com.github.moaxcp.x11client.protocol.present;
    exports com.github.moaxcp.x11client.protocol.randr;
    exports com.github.moaxcp.x11client.protocol.record;
    exports com.github.moaxcp.x11client.protocol.render;
    exports com.github.moaxcp.x11client.protocol.res;
    exports com.github.moaxcp.x11client.protocol.screensaver;
    exports com.github.moaxcp.x11client.protocol.shape;
    exports com.github.moaxcp.x11client.protocol.shm;
    exports com.github.moaxcp.x11client.protocol.sync;
    exports com.github.moaxcp.x11client.protocol.xc_misc;
    exports com.github.moaxcp.x11client.protocol.xevie;
    exports com.github.moaxcp.x11client.protocol.xf86dri;
    exports com.github.moaxcp.x11client.protocol.xf86vidmode;
    exports com.github.moaxcp.x11client.protocol.xfixes;
    exports com.github.moaxcp.x11client.protocol.xinerama;
    exports com.github.moaxcp.x11client.protocol.xinput;
    exports com.github.moaxcp.x11client.protocol.xkb;
    exports com.github.moaxcp.x11client.protocol.xprint;
    exports com.github.moaxcp.x11client.protocol.xselinux;
    exports com.github.moaxcp.x11client.protocol.xtest;
    exports com.github.moaxcp.x11client.protocol.xv;
    exports com.github.moaxcp.x11client.protocol.xvmc;
}