package com.github.moaxcp.x11protocol.parser

import com.squareup.javapoet.ArrayTypeName
import com.squareup.javapoet.CodeBlock
import com.squareup.javapoet.TypeName
import groovy.transform.EqualsAndHashCode
import groovy.transform.ToString

@ToString(includePackage = false)
@EqualsAndHashCode
class JavaPad implements JavaUnit {
    JavaType javaType
    XUnit xUnit
    int bytes
    boolean readParam

    @Override
    XUnit getXUnit() { //todo why is this not generated by groovy
        return xUnit
    }

    @Override
    TypeName getTypeName() {
        return ArrayTypeName.of(byte.class)
    }

    @Override
    CodeBlock getDeclareAndReadCode() {
        return CodeBlock.builder().addStatement(getReadCode()).build()
    }

    @Override
    CodeBlock getReadCode() {
        CodeBlock.of("in.readPad($bytes)")
    }

    @Override
    CodeBlock getWriteCode() {
        return CodeBlock.builder().addStatement("out.writePad($bytes)").build()
    }

    @Override
    CodeBlock getSizeExpression() {
        return CodeBlock.of('$L', bytes)
    }

    @Override
    Optional<Integer> getFixedSize() {
        return Optional.of(bytes)
    }
}
