package com.github.moaxcp.x11protocol.parser

import com.squareup.javapoet.CodeBlock
import groovy.transform.EqualsAndHashCode
import groovy.transform.ToString

@ToString(includePackage = false)
@EqualsAndHashCode
class JavaPad implements JavaUnit {
    JavaType javaType
    XUnit xUnit
    int bytes
    
    XUnit getXUnit() { //todo why is this not generated by groovy
        return xUnit
    }

    @Override
    CodeBlock getReadCode() {
        return CodeBlock.builder().addStatement("in.readPad($bytes)").build()
    }

    @Override
    CodeBlock getWriteCode() {
        return CodeBlock.builder().addStatement("out.writePad($bytes)").build()
    }

    @Override
    CodeBlock getSize() {
        return CodeBlock.of('$L', bytes)
    }
}
