package com.github.moaxcp.x11protocol.parser

import com.squareup.javapoet.CodeBlock

class JavaRequiredStartAlign implements JavaUnit {
    JavaType javaType
    XUnit xUnit
    int align

    XUnit getXUnit() { //todo why is this not generated by groovy
        return xUnit
    }

    @Override
    CodeBlock getReadCode() {
        return CodeBlock.of('//todo align')
    }

    @Override
    CodeBlock getWriteCode() {
        return CodeBlock.of('//todo align')
    }

    @Override
    CodeBlock getSizeExpression() {
        return CodeBlock.of('$L', 0)
    }

    @Override
    Optional<Integer> getFixedSize() {
        throw new UnsupportedOperationException('not supported')
    }
}
