package com.github.moaxcp.x11protocol.parser

import com.squareup.javapoet.CodeBlock
import com.squareup.javapoet.TypeName

class JavaPadAlign implements JavaUnit {
    JavaType javaType
    XUnit xUnit
    int align
    JavaListProperty list

    XUnit getXUnit() { //todo why is this not generated by groovy
        return xUnit
    }

    @Override
    CodeBlock getReadCode() {
        if(align == 4) {
            return CodeBlock.builder()
                .addStatement("in.readPadAlign(${list.lengthExpression.getExpression(TypeName.INT)})")
                .build()
        }
        return CodeBlock.builder()
            .addStatement("in.readPadAlign($align, ${list.lengthExpression.getExpression(TypeName.INT)})")
            .build()
    }

    @Override
    CodeBlock getWriteCode() {
        if(align == 4) {
            return CodeBlock.builder()
                .addStatement("out.writePadAlign(${list.lengthExpression.getExpression(TypeName.INT)})")
                .build()
        }
        return CodeBlock.builder()
            .addStatement("out.writePadAlign($align, ${list.lengthExpression.getExpression(TypeName.INT)})")
            .build()

    }

    @Override
    CodeBlock getSizeExpression() {
        return CodeBlock.of('$L', 0)
    }

    @Override
    Optional<Integer> getFixedSize() {
        return null
    }
}
